// flow-typed signature: 6c1c833aa1ff78f2512baf2d3c4e9f57
// flow-typed version: <<STUB>>/video.js_v^6.2.5/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'video.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'video.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'video.js/dist/alt/video.novtt' {
  declare module.exports: any;
}

declare module 'video.js/dist/alt/video.novtt.min' {
  declare module.exports: any;
}

declare module 'video.js/dist/ie8/videojs-ie8' {
  declare module.exports: any;
}

declare module 'video.js/dist/ie8/videojs-ie8.min' {
  declare module.exports: any;
}

declare module 'video.js/dist/lang/ar' {
  declare module.exports: any;
}

declare module 'video.js/dist/lang/ba' {
  declare module.exports: any;
}

declare module 'video.js/dist/lang/bg' {
  declare module.exports: any;
}

declare module 'video.js/dist/lang/ca' {
  declare module.exports: any;
}

declare module 'video.js/dist/lang/cs' {
  declare module.exports: any;
}

declare module 'video.js/dist/lang/da' {
  declare module.exports: any;
}

declare module 'video.js/dist/lang/de' {
  declare module.exports: any;
}

declare module 'video.js/dist/lang/el' {
  declare module.exports: any;
}

declare module 'video.js/dist/lang/en' {
  declare module.exports: any;
}

declare module 'video.js/dist/lang/es' {
  declare module.exports: any;
}

declare module 'video.js/dist/lang/fa' {
  declare module.exports: any;
}

declare module 'video.js/dist/lang/fi' {
  declare module.exports: any;
}

declare module 'video.js/dist/lang/fr' {
  declare module.exports: any;
}

declare module 'video.js/dist/lang/gl' {
  declare module.exports: any;
}

declare module 'video.js/dist/lang/hr' {
  declare module.exports: any;
}

declare module 'video.js/dist/lang/hu' {
  declare module.exports: any;
}

declare module 'video.js/dist/lang/it' {
  declare module.exports: any;
}

declare module 'video.js/dist/lang/ja' {
  declare module.exports: any;
}

declare module 'video.js/dist/lang/ko' {
  declare module.exports: any;
}

declare module 'video.js/dist/lang/nb' {
  declare module.exports: any;
}

declare module 'video.js/dist/lang/nl' {
  declare module.exports: any;
}

declare module 'video.js/dist/lang/nn' {
  declare module.exports: any;
}

declare module 'video.js/dist/lang/pl' {
  declare module.exports: any;
}

declare module 'video.js/dist/lang/pt-BR' {
  declare module.exports: any;
}

declare module 'video.js/dist/lang/pt-PT' {
  declare module.exports: any;
}

declare module 'video.js/dist/lang/ru' {
  declare module.exports: any;
}

declare module 'video.js/dist/lang/sk' {
  declare module.exports: any;
}

declare module 'video.js/dist/lang/sr' {
  declare module.exports: any;
}

declare module 'video.js/dist/lang/sv' {
  declare module.exports: any;
}

declare module 'video.js/dist/lang/tr' {
  declare module.exports: any;
}

declare module 'video.js/dist/lang/uk' {
  declare module.exports: any;
}

declare module 'video.js/dist/lang/vi' {
  declare module.exports: any;
}

declare module 'video.js/dist/lang/zh-CN' {
  declare module.exports: any;
}

declare module 'video.js/dist/lang/zh-TW' {
  declare module.exports: any;
}

declare module 'video.js/dist/video.cjs' {
  declare module.exports: any;
}

declare module 'video.js/dist/video.es' {
  declare module.exports: any;
}

declare module 'video.js/dist/video' {
  declare module.exports: any;
}

declare module 'video.js/dist/video.min' {
  declare module.exports: any;
}

declare module 'video.js/docs/api/scripts/jquery.min' {
  declare module.exports: any;
}

declare module 'video.js/docs/api/scripts/linenumber' {
  declare module.exports: any;
}

declare module 'video.js/docs/api/scripts/prettify/lang-css' {
  declare module.exports: any;
}

declare module 'video.js/docs/api/scripts/prettify/prettify' {
  declare module.exports: any;
}

declare module 'video.js/docs/api/scripts/tui-doc' {
  declare module.exports: any;
}

// Filename aliases
declare module 'video.js/dist/alt/video.novtt.js' {
  declare module.exports: $Exports<'video.js/dist/alt/video.novtt'>;
}
declare module 'video.js/dist/alt/video.novtt.min.js' {
  declare module.exports: $Exports<'video.js/dist/alt/video.novtt.min'>;
}
declare module 'video.js/dist/ie8/videojs-ie8.js' {
  declare module.exports: $Exports<'video.js/dist/ie8/videojs-ie8'>;
}
declare module 'video.js/dist/ie8/videojs-ie8.min.js' {
  declare module.exports: $Exports<'video.js/dist/ie8/videojs-ie8.min'>;
}
declare module 'video.js/dist/lang/ar.js' {
  declare module.exports: $Exports<'video.js/dist/lang/ar'>;
}
declare module 'video.js/dist/lang/ba.js' {
  declare module.exports: $Exports<'video.js/dist/lang/ba'>;
}
declare module 'video.js/dist/lang/bg.js' {
  declare module.exports: $Exports<'video.js/dist/lang/bg'>;
}
declare module 'video.js/dist/lang/ca.js' {
  declare module.exports: $Exports<'video.js/dist/lang/ca'>;
}
declare module 'video.js/dist/lang/cs.js' {
  declare module.exports: $Exports<'video.js/dist/lang/cs'>;
}
declare module 'video.js/dist/lang/da.js' {
  declare module.exports: $Exports<'video.js/dist/lang/da'>;
}
declare module 'video.js/dist/lang/de.js' {
  declare module.exports: $Exports<'video.js/dist/lang/de'>;
}
declare module 'video.js/dist/lang/el.js' {
  declare module.exports: $Exports<'video.js/dist/lang/el'>;
}
declare module 'video.js/dist/lang/en.js' {
  declare module.exports: $Exports<'video.js/dist/lang/en'>;
}
declare module 'video.js/dist/lang/es.js' {
  declare module.exports: $Exports<'video.js/dist/lang/es'>;
}
declare module 'video.js/dist/lang/fa.js' {
  declare module.exports: $Exports<'video.js/dist/lang/fa'>;
}
declare module 'video.js/dist/lang/fi.js' {
  declare module.exports: $Exports<'video.js/dist/lang/fi'>;
}
declare module 'video.js/dist/lang/fr.js' {
  declare module.exports: $Exports<'video.js/dist/lang/fr'>;
}
declare module 'video.js/dist/lang/gl.js' {
  declare module.exports: $Exports<'video.js/dist/lang/gl'>;
}
declare module 'video.js/dist/lang/hr.js' {
  declare module.exports: $Exports<'video.js/dist/lang/hr'>;
}
declare module 'video.js/dist/lang/hu.js' {
  declare module.exports: $Exports<'video.js/dist/lang/hu'>;
}
declare module 'video.js/dist/lang/it.js' {
  declare module.exports: $Exports<'video.js/dist/lang/it'>;
}
declare module 'video.js/dist/lang/ja.js' {
  declare module.exports: $Exports<'video.js/dist/lang/ja'>;
}
declare module 'video.js/dist/lang/ko.js' {
  declare module.exports: $Exports<'video.js/dist/lang/ko'>;
}
declare module 'video.js/dist/lang/nb.js' {
  declare module.exports: $Exports<'video.js/dist/lang/nb'>;
}
declare module 'video.js/dist/lang/nl.js' {
  declare module.exports: $Exports<'video.js/dist/lang/nl'>;
}
declare module 'video.js/dist/lang/nn.js' {
  declare module.exports: $Exports<'video.js/dist/lang/nn'>;
}
declare module 'video.js/dist/lang/pl.js' {
  declare module.exports: $Exports<'video.js/dist/lang/pl'>;
}
declare module 'video.js/dist/lang/pt-BR.js' {
  declare module.exports: $Exports<'video.js/dist/lang/pt-BR'>;
}
declare module 'video.js/dist/lang/pt-PT.js' {
  declare module.exports: $Exports<'video.js/dist/lang/pt-PT'>;
}
declare module 'video.js/dist/lang/ru.js' {
  declare module.exports: $Exports<'video.js/dist/lang/ru'>;
}
declare module 'video.js/dist/lang/sk.js' {
  declare module.exports: $Exports<'video.js/dist/lang/sk'>;
}
declare module 'video.js/dist/lang/sr.js' {
  declare module.exports: $Exports<'video.js/dist/lang/sr'>;
}
declare module 'video.js/dist/lang/sv.js' {
  declare module.exports: $Exports<'video.js/dist/lang/sv'>;
}
declare module 'video.js/dist/lang/tr.js' {
  declare module.exports: $Exports<'video.js/dist/lang/tr'>;
}
declare module 'video.js/dist/lang/uk.js' {
  declare module.exports: $Exports<'video.js/dist/lang/uk'>;
}
declare module 'video.js/dist/lang/vi.js' {
  declare module.exports: $Exports<'video.js/dist/lang/vi'>;
}
declare module 'video.js/dist/lang/zh-CN.js' {
  declare module.exports: $Exports<'video.js/dist/lang/zh-CN'>;
}
declare module 'video.js/dist/lang/zh-TW.js' {
  declare module.exports: $Exports<'video.js/dist/lang/zh-TW'>;
}
declare module 'video.js/dist/video.cjs.js' {
  declare module.exports: $Exports<'video.js/dist/video.cjs'>;
}
declare module 'video.js/dist/video.es.js' {
  declare module.exports: $Exports<'video.js/dist/video.es'>;
}
declare module 'video.js/dist/video.js' {
  declare module.exports: $Exports<'video.js/dist/video'>;
}
declare module 'video.js/dist/video.min.js' {
  declare module.exports: $Exports<'video.js/dist/video.min'>;
}
declare module 'video.js/docs/api/scripts/jquery.min.js' {
  declare module.exports: $Exports<'video.js/docs/api/scripts/jquery.min'>;
}
declare module 'video.js/docs/api/scripts/linenumber.js' {
  declare module.exports: $Exports<'video.js/docs/api/scripts/linenumber'>;
}
declare module 'video.js/docs/api/scripts/prettify/lang-css.js' {
  declare module.exports: $Exports<'video.js/docs/api/scripts/prettify/lang-css'>;
}
declare module 'video.js/docs/api/scripts/prettify/prettify.js' {
  declare module.exports: $Exports<'video.js/docs/api/scripts/prettify/prettify'>;
}
declare module 'video.js/docs/api/scripts/tui-doc.js' {
  declare module.exports: $Exports<'video.js/docs/api/scripts/tui-doc'>;
}
