// flow-typed signature: b1f3bd6bc94535ee6e04c3d4ee5ad10b
// flow-typed version: <<STUB>>/@terse/webpack_v^1.0.7/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@terse/webpack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@terse/webpack' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@terse/webpack/dist/api' {
  declare module.exports: any;
}

declare module '@terse/webpack/dist/bin/components/App' {
  declare module.exports: any;
}

declare module '@terse/webpack/dist/bin/components/Check' {
  declare module.exports: any;
}

declare module '@terse/webpack/dist/bin/components/Code' {
  declare module.exports: any;
}

declare module '@terse/webpack/dist/bin/components/Footer' {
  declare module.exports: any;
}

declare module '@terse/webpack/dist/bin/components/Header' {
  declare module.exports: any;
}

declare module '@terse/webpack/dist/bin/components/SaveButton' {
  declare module.exports: any;
}

declare module '@terse/webpack/dist/bin/components/Step' {
  declare module.exports: any;
}

declare module '@terse/webpack/dist/bin/components/Steps' {
  declare module.exports: any;
}

declare module '@terse/webpack/dist/bin/config' {
  declare module.exports: any;
}

declare module '@terse/webpack/dist/bin/main' {
  declare module.exports: any;
}

declare module '@terse/webpack/dist/bin/state' {
  declare module.exports: any;
}

declare module '@terse/webpack/dist/bin/terse-webpack' {
  declare module.exports: any;
}

declare module '@terse/webpack/dist/bin/webpack' {
  declare module.exports: any;
}

declare module '@terse/webpack/dist/Expression' {
  declare module.exports: any;
}

declare module '@terse/webpack/dist/features/alias' {
  declare module.exports: any;
}

declare module '@terse/webpack/dist/features/context' {
  declare module.exports: any;
}

declare module '@terse/webpack/dist/features/entry' {
  declare module.exports: any;
}

declare module '@terse/webpack/dist/features/env' {
  declare module.exports: any;
}

declare module '@terse/webpack/dist/features/externals' {
  declare module.exports: any;
}

declare module '@terse/webpack/dist/features/index' {
  declare module.exports: any;
}

declare module '@terse/webpack/dist/features/loader' {
  declare module.exports: any;
}

declare module '@terse/webpack/dist/features/modules' {
  declare module.exports: any;
}

declare module '@terse/webpack/dist/features/node' {
  declare module.exports: any;
}

declare module '@terse/webpack/dist/features/output' {
  declare module.exports: any;
}

declare module '@terse/webpack/dist/features/plugin' {
  declare module.exports: any;
}

declare module '@terse/webpack/dist/features/preLoader' {
  declare module.exports: any;
}

declare module '@terse/webpack/dist/features/sourcemap' {
  declare module.exports: any;
}

declare module '@terse/webpack/dist/features/target' {
  declare module.exports: any;
}

declare module '@terse/webpack/dist/index' {
  declare module.exports: any;
}

declare module '@terse/webpack/dist/Plugin' {
  declare module.exports: any;
}

declare module '@terse/webpack/dist/reducers/cache' {
  declare module.exports: any;
}

declare module '@terse/webpack/dist/reducers/devtool' {
  declare module.exports: any;
}

declare module '@terse/webpack/dist/reducers/entry' {
  declare module.exports: any;
}

declare module '@terse/webpack/dist/reducers/externals' {
  declare module.exports: any;
}

declare module '@terse/webpack/dist/reducers/index' {
  declare module.exports: any;
}

declare module '@terse/webpack/dist/reducers/module' {
  declare module.exports: any;
}

declare module '@terse/webpack/dist/reducers/node' {
  declare module.exports: any;
}

declare module '@terse/webpack/dist/reducers/output' {
  declare module.exports: any;
}

declare module '@terse/webpack/dist/reducers/plugins' {
  declare module.exports: any;
}

declare module '@terse/webpack/dist/reducers/resolve' {
  declare module.exports: any;
}

declare module '@terse/webpack/dist/reducers/target' {
  declare module.exports: any;
}

declare module '@terse/webpack/dist/stringify' {
  declare module.exports: any;
}

// Filename aliases
declare module '@terse/webpack/dist/api.js' {
  declare module.exports: $Exports<'@terse/webpack/dist/api'>;
}
declare module '@terse/webpack/dist/bin/components/App.js' {
  declare module.exports: $Exports<'@terse/webpack/dist/bin/components/App'>;
}
declare module '@terse/webpack/dist/bin/components/Check.js' {
  declare module.exports: $Exports<'@terse/webpack/dist/bin/components/Check'>;
}
declare module '@terse/webpack/dist/bin/components/Code.js' {
  declare module.exports: $Exports<'@terse/webpack/dist/bin/components/Code'>;
}
declare module '@terse/webpack/dist/bin/components/Footer.js' {
  declare module.exports: $Exports<'@terse/webpack/dist/bin/components/Footer'>;
}
declare module '@terse/webpack/dist/bin/components/Header.js' {
  declare module.exports: $Exports<'@terse/webpack/dist/bin/components/Header'>;
}
declare module '@terse/webpack/dist/bin/components/SaveButton.js' {
  declare module.exports: $Exports<'@terse/webpack/dist/bin/components/SaveButton'>;
}
declare module '@terse/webpack/dist/bin/components/Step.js' {
  declare module.exports: $Exports<'@terse/webpack/dist/bin/components/Step'>;
}
declare module '@terse/webpack/dist/bin/components/Steps.js' {
  declare module.exports: $Exports<'@terse/webpack/dist/bin/components/Steps'>;
}
declare module '@terse/webpack/dist/bin/config.js' {
  declare module.exports: $Exports<'@terse/webpack/dist/bin/config'>;
}
declare module '@terse/webpack/dist/bin/main.js' {
  declare module.exports: $Exports<'@terse/webpack/dist/bin/main'>;
}
declare module '@terse/webpack/dist/bin/state.js' {
  declare module.exports: $Exports<'@terse/webpack/dist/bin/state'>;
}
declare module '@terse/webpack/dist/bin/terse-webpack.js' {
  declare module.exports: $Exports<'@terse/webpack/dist/bin/terse-webpack'>;
}
declare module '@terse/webpack/dist/bin/webpack.js' {
  declare module.exports: $Exports<'@terse/webpack/dist/bin/webpack'>;
}
declare module '@terse/webpack/dist/Expression.js' {
  declare module.exports: $Exports<'@terse/webpack/dist/Expression'>;
}
declare module '@terse/webpack/dist/features/alias.js' {
  declare module.exports: $Exports<'@terse/webpack/dist/features/alias'>;
}
declare module '@terse/webpack/dist/features/context.js' {
  declare module.exports: $Exports<'@terse/webpack/dist/features/context'>;
}
declare module '@terse/webpack/dist/features/entry.js' {
  declare module.exports: $Exports<'@terse/webpack/dist/features/entry'>;
}
declare module '@terse/webpack/dist/features/env.js' {
  declare module.exports: $Exports<'@terse/webpack/dist/features/env'>;
}
declare module '@terse/webpack/dist/features/externals.js' {
  declare module.exports: $Exports<'@terse/webpack/dist/features/externals'>;
}
declare module '@terse/webpack/dist/features/index.js' {
  declare module.exports: $Exports<'@terse/webpack/dist/features/index'>;
}
declare module '@terse/webpack/dist/features/loader.js' {
  declare module.exports: $Exports<'@terse/webpack/dist/features/loader'>;
}
declare module '@terse/webpack/dist/features/modules.js' {
  declare module.exports: $Exports<'@terse/webpack/dist/features/modules'>;
}
declare module '@terse/webpack/dist/features/node.js' {
  declare module.exports: $Exports<'@terse/webpack/dist/features/node'>;
}
declare module '@terse/webpack/dist/features/output.js' {
  declare module.exports: $Exports<'@terse/webpack/dist/features/output'>;
}
declare module '@terse/webpack/dist/features/plugin.js' {
  declare module.exports: $Exports<'@terse/webpack/dist/features/plugin'>;
}
declare module '@terse/webpack/dist/features/preLoader.js' {
  declare module.exports: $Exports<'@terse/webpack/dist/features/preLoader'>;
}
declare module '@terse/webpack/dist/features/sourcemap.js' {
  declare module.exports: $Exports<'@terse/webpack/dist/features/sourcemap'>;
}
declare module '@terse/webpack/dist/features/target.js' {
  declare module.exports: $Exports<'@terse/webpack/dist/features/target'>;
}
declare module '@terse/webpack/dist/index.js' {
  declare module.exports: $Exports<'@terse/webpack/dist/index'>;
}
declare module '@terse/webpack/dist/Plugin.js' {
  declare module.exports: $Exports<'@terse/webpack/dist/Plugin'>;
}
declare module '@terse/webpack/dist/reducers/cache.js' {
  declare module.exports: $Exports<'@terse/webpack/dist/reducers/cache'>;
}
declare module '@terse/webpack/dist/reducers/devtool.js' {
  declare module.exports: $Exports<'@terse/webpack/dist/reducers/devtool'>;
}
declare module '@terse/webpack/dist/reducers/entry.js' {
  declare module.exports: $Exports<'@terse/webpack/dist/reducers/entry'>;
}
declare module '@terse/webpack/dist/reducers/externals.js' {
  declare module.exports: $Exports<'@terse/webpack/dist/reducers/externals'>;
}
declare module '@terse/webpack/dist/reducers/index.js' {
  declare module.exports: $Exports<'@terse/webpack/dist/reducers/index'>;
}
declare module '@terse/webpack/dist/reducers/module.js' {
  declare module.exports: $Exports<'@terse/webpack/dist/reducers/module'>;
}
declare module '@terse/webpack/dist/reducers/node.js' {
  declare module.exports: $Exports<'@terse/webpack/dist/reducers/node'>;
}
declare module '@terse/webpack/dist/reducers/output.js' {
  declare module.exports: $Exports<'@terse/webpack/dist/reducers/output'>;
}
declare module '@terse/webpack/dist/reducers/plugins.js' {
  declare module.exports: $Exports<'@terse/webpack/dist/reducers/plugins'>;
}
declare module '@terse/webpack/dist/reducers/resolve.js' {
  declare module.exports: $Exports<'@terse/webpack/dist/reducers/resolve'>;
}
declare module '@terse/webpack/dist/reducers/target.js' {
  declare module.exports: $Exports<'@terse/webpack/dist/reducers/target'>;
}
declare module '@terse/webpack/dist/stringify.js' {
  declare module.exports: $Exports<'@terse/webpack/dist/stringify'>;
}
